webapp/views/home.py
from flask import Blueprint
from flask import request, abort, redirect, session, make_response
from services import render, identity
from models.user import User
from models.news import News
import json
import uuid
module = Blueprint('home', __name__)


@module.route('/')
def index():
    user = {}
    if session.get('user') is not None:
        user = json.loads(session.get("user"))

    return render.template('sites/index.html', user=user)


@module.route('/x-6')
def x6():
    return render.template('sites/x-6.html')


@module.route('/x-8')
def x8():
    return render.template('sites/x-8.html')


@module.route('/x-4')
def x4():
    return render.template('sites/x-4.html')


@module.route('/login', methods=['GET'])
def login():
    return render.template('home/login.html')


@module.route('/login', methods=['POST'])
def do_login():
    data = request.form.to_dict()
    username = data.get('username', None)
    password = data.get('password', None)
    if identity.authenticate(username, password):
        resp = make_response(redirect(request.args.get('next', '/')))
        if json.loads(session['user']).get('permission', 1) > 2:
            userId = json.loads(session.get('user')).get('_id').get('$oid')
            sid = str(uuid.uuid4())
            user = User.objects(id=userId).get()
            user.sid = sid
            user.save()
            user.reload()
            session['user'] = user.to_json()
            resp.set_cookie('userId', userId)
            resp.set_cookie('sid', sid)
        return resp
    else:
        return render.template('home/login.html')


@module.route('/logout')
def logout():
    identity.logout()
    resp = make_response(redirect("/"))
    resp.set_cookie('sid', expires=0)
    resp.set_cookie('userId', expires=0)
    return resp

webapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            {% block title %}<title></title>{% endblock %}
            <link rel="stylesheet" href="./static/vendor/foundation/css/foundation.css" />
            <link rel="stylesheet" href="./static/vendor/foundation/css/normalize.css" />
            <script src="./static/vendor/foundation/js/vendor/modernizr.js"></script>
        {% endblock%}
    </head>
    <body>
        <section id="header">
            <div id="first-menu" class="show-for-large-up" >
                <div class="row">
                    <ul class="inline-list left">
                        <li><a href="/"><img src="./static/img/logo.png" alt="" style="height:50px;margin-top:5px;margin-right:10px;margin-left:20px;"></a></li>
                    </ul>
                    <ul class="inline-list right">
                        <li><a href="{{ url_for('home.index') }}">Trang Chủ</a></li>
                        <li><a href="{{ url_for('home.x4') }}">X-Fone X-4</a></li>
                        <li><a href="{{ url_for('home.x6') }}">X-Fone X-6</a></li>
                        <li><a href="{{ url_for('home.x8') }}">X-Fone X-8</a></li>
                        <li><a href="#" data-reveal-id="firstModal" >Hệ Thống</a></li>
                        <li><a href="#" data-reveal-id="thanhtoan">Hỗ Trợ </a></li>
                    </ul>
                </ul>
            </div>
        </div>
        <div class="off-canvas-wrap" data-offcanvas>
            <div class="inner-wrap">
                <nav class="tab-bar hide-for-large-up">
                    <section class="left-small">
                        <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
                    </section>
                    <section class="middle tab-bar-section">
                        <a href="" title="home">
                            <img src="./static/img/logo.png" alt="" style="height:41px;margin-top:4px;">
                        </a>
                    </section>
                </nav>
                <aside class="left-off-canvas-menu hide-for-large-up">
                    <ul class="off-canvas-list">
                        <li><label>DANH MỤC SẢN PHẨM</label></li>
                        <li><a href="{{ url_for('home.index') }}">Trang Chủ</a></li>
                        <li><a href="{{ url_for('home.x4') }}">X-4 Mobile</a></li>
                        <li><a href="{{ url_for('home.x6') }}">X-6 Mobile</a></li>
                        <li><a href="{{ url_for('home.x8') }}">X-8 Mobile</a></li>
                        <li><a href="#" data-reveal-id="firstModal">Hệ Thống Siêu Thị</a></li>
                        <li><a href="#" data-reveal-id="thanhtoan">Hỗ Trợ</a></li>
                    </ul>
                </aside>
                
                <a class="exit-off-canvas"></a>
            </div>
        </div>
    </section>
    <section class="main-section">
                    <!-- content goes here -->
                    <div class="row">
                        {% block slides %}
                            
                        {% endblock %}
                    </div>
                    <div class="row">
                        {% block hi %}

                        {% endblock %}
                    </div>
                    <div class="row">
                        {% block khung %}
                        {% endblock %}
                    </div>
                </section>
    <div id="social">
        <ul>
            <li><a href="https://www.facebook.com/pages/Smartphone-gi%C3%A1-r%E1%BA%BB-nh%E1%BA%A5t/757846657636925?ref=hl" title="Facebook"><img src="./static/img/facebook.png" alt=""></a></li>
            <li><a href="#" title="Google"><img src="./static/img/google.png" alt=""></a></li>
            <li><a href="https://www.youtube.com/watch?v=VJG6A54YbEE" title="Youtube"><img src="./static/img/youtube.png" alt=""></a></li>
        </ul>
    </div>
    <!-- ********************************************* -->
    {% block hotro %}
        {% include "sites/temp.html" %}
        {% include "sites/trungtam.html" %}
    {% endblock %}
    
    <script src="./static/vendor/foundation/js/vendor/jquery.js"></script>
    <script src="./static/vendor/foundation/js/foundation.min.js"></script>
    <script src="./static/vendor/foundation/js/foundation/foundation.equalizer.js"></script>
    <script src="./static/vendor/foundation/js/foundation/foundation.offcanvas.js"></script>
    <link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="./static/css/footer.css" />
    <link rel="stylesheet" href="./static/css/layout.css" />
    <link rel="stylesheet" href="./static/css/menu.css" />
    <link rel="stylesheet" href="./static/css/home.css" />
    <script>
    $(document).foundation();
    </script>
</body>
</html>